In [1]:
import torch

In [2]:
x = torch.empty(1) # empty tensor

In [3]:
x

tensor([-1.2254e-36])

In [10]:
x = torch.empty(2,2,3,1)
x

tensor([[[[-1.2254e-36],
          [ 3.0611e-41],
          [ 1.5975e-43]],

         [[ 1.3873e-43],
          [ 1.4574e-43],
          [ 6.4460e-44]]],


        [[[ 1.4153e-43],
          [ 1.5274e-43],
          [ 1.5695e-43]],

         [[ 1.6255e-43],
          [ 1.6956e-43],
          [ 0.0000e+00]]]])

In [19]:
x = torch.rand(2,3, dtype = torch.float16)
x

tensor([[0.8359, 0.1582, 0.9385],
        [0.6074, 0.6187, 0.8877]], dtype=torch.float16)

In [14]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [20]:
x = torch.tensor([2.5, 0.1])

In [21]:
x

tensor([2.5000, 0.1000])

In [22]:
a = torch.ones(5)

In [23]:
a

tensor([1., 1., 1., 1., 1.])

In [24]:
b = a.numpy()

In [25]:
b

array([1., 1., 1., 1., 1.], dtype=float32)

In [26]:
type(b)

numpy.ndarray

In [27]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [28]:
a

tensor([2., 2., 2., 2., 2.])

In [29]:
b

array([2., 2., 2., 2., 2.], dtype=float32)

In [30]:
c = torch.from_numpy(b)

In [31]:
type(c)

torch.Tensor

In [33]:
if  torch.cuda.is_available():
  device = torch.device("cuda")


In [34]:
print(device)

cuda


In [38]:
x = torch.ones(5,device= device)
y = torch.ones(5)
y = y.to(device)
z = x + y
#numpy can only cpu tensor not GPU tensor
z= z.to("cpu")

In [39]:
z

tensor([2., 2., 2., 2., 2.])

In [40]:
x = torch.ones(3, requires_grad= True)
#default its false, specify grad = True

In [41]:
x

tensor([1., 1., 1.], requires_grad=True)