<a href="https://colab.research.google.com/github/mspatke/Deep-Learning-with-Pytorch/blob/main/7_DataLoader.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Epoch = 1 forward and backward pass of all training samples

batch_size = no. of training samples in one forward and backward pass

no of iterations = no of passes, each pass using [batch_size] no of samples

eg,100 samples, batch_size=20 --> 100/20 = 5 iteration for 1 epoch

In [56]:
import torch
import torchvision
from torch.utils.data import Dataset, DataLoader
import numpy as np
import math

In [57]:
class WineDataset(Dataset):

  def __init__(self):

    xy= np.loadtxt('wine.csv', delimiter=',', dtype = np.float32, skiprows=1)
    self.n_samples= xy.shape[0]

    self.x_data= torch.from_numpy(xy[:,1:])   
    self.y_data= torch.from_numpy(xy[:,[0]])
                                  
  def __getitem__(self, index):
    return self.x_data[index], self.y_data[index]

  def __len__(self):
    return self.n_samples
                                  


In [ ]:
dataset = WineDataset()

In [ ]:
first = dataset[0]
features, labels = first

In [ ]:
features

tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03])

In [ ]:
labels

tensor([1.])

In [ ]:
train_loader = DataLoader(dataset = dataset,
                          batch_size=4,
                          shuffle=True,
                          num_workers=2)

In [ ]:
dataiter=iter(train_loader)
data = dataiter.next()
features, labels = data

In [ ]:
print(features, labels)

tensor([[1.4020e+01, 1.6800e+00, 2.2100e+00, 1.6000e+01, 9.6000e+01, 2.6500e+00,
         2.3300e+00, 2.6000e-01, 1.9800e+00, 4.7000e+00, 1.0400e+00, 3.5900e+00,
         1.0350e+03],
        [1.3480e+01, 1.6700e+00, 2.6400e+00, 2.2500e+01, 8.9000e+01, 2.6000e+00,
         1.1000e+00, 5.2000e-01, 2.2900e+00, 1.1750e+01, 5.7000e-01, 1.7800e+00,
         6.2000e+02],
        [1.2790e+01, 2.6700e+00, 2.4800e+00, 2.2000e+01, 1.1200e+02, 1.4800e+00,
         1.3600e+00, 2.4000e-01, 1.2600e+00, 1.0800e+01, 4.8000e-01, 1.4700e+00,
         4.8000e+02],
        [1.3560e+01, 1.7300e+00, 2.4600e+00, 2.0500e+01, 1.1600e+02, 2.9600e+00,
         2.7800e+00, 2.0000e-01, 2.4500e+00, 6.2500e+00, 9.8000e-01, 3.0300e+00,
         1.1200e+03]]) tensor([[1.],
        [3.],
        [3.],
        [1.]])


In [ ]:
#dummy training loop

epochs=2
total_samples = len(dataset)
n_iterations = math.ceil(total_samples/4)

for epoch in range(epochs):
  for i, (inputs, labels) in enumerate(train_loader):

    if(i+1) % 5 ==0:
      print(f'Epoch :{epoch+1}/{epochs}, Step {i+1}/{n_iterations}| Inputs {inputs.shape} | Labels {labels.shape}')


Epoch :1/2, Step 5/45| Inputs torch.Size([4, 13]) | Labels torch.Size([4, 1])
Epoch :1/2, Step 10/45| Inputs torch.Size([4, 13]) | Labels torch.Size([4, 1])
Epoch :1/2, Step 15/45| Inputs torch.Size([4, 13]) | Labels torch.Size([4, 1])
Epoch :1/2, Step 20/45| Inputs torch.Size([4, 13]) | Labels torch.Size([4, 1])
Epoch :1/2, Step 25/45| Inputs torch.Size([4, 13]) | Labels torch.Size([4, 1])
Epoch :1/2, Step 30/45| Inputs torch.Size([4, 13]) | Labels torch.Size([4, 1])
Epoch :1/2, Step 35/45| Inputs torch.Size([4, 13]) | Labels torch.Size([4, 1])
Epoch :1/2, Step 40/45| Inputs torch.Size([4, 13]) | Labels torch.Size([4, 1])
Epoch :1/2, Step 45/45| Inputs torch.Size([2, 13]) | Labels torch.Size([2, 1])
Epoch :2/2, Step 5/45| Inputs torch.Size([4, 13]) | Labels torch.Size([4, 1])
Epoch :2/2, Step 10/45| Inputs torch.Size([4, 13]) | Labels torch.Size([4, 1])
Epoch :2/2, Step 15/45| Inputs torch.Size([4, 13]) | Labels torch.Size([4, 1])
Epoch :2/2, Step 20/45| Inputs torch.Size([4, 13]) | L

In [ ]:
total_samples, n_iterations

(178, 45)

In [ ]:

train_dataset = torchvision.datasets.MNIST(root ='./data',
                                           train= True,
                                           transform=torchvision.transforms.ToTensor(),
                                           download=True)

train_loader = DataLoader(dataset=train_dataset,
                          batch_size=3,
                          shuffle=True)

In [ ]:
dataitr = iter(train_loader)
data = dataitr.next()
inputs, targets = data
print(inputs.shape, targets.shape)

torch.Size([3, 1, 28, 28]) torch.Size([3])
